runtime: python37
handlers:
- url: /static
  static_dir: static/ # This handler routes all requests not caught above to the main app. 
- url: /.*
  script: auto
entrypoint: gunicorn -b :$PORT app.app.wsgi:application
env_variables:
  DJANGO_SETTINGS_MODULE: "app.app.settings"
  DJANGO_CONFIGURATION: "Deploy"