branch-defaults:
  master:
    environment: smart-sheets-backend-dev
    group_suffix: null
global:
  application_name: smart-sheets-backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 (BETA)
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
